### ISSUE TITLE
Experiments/Cleanup/Todos 17/11 Discussion

### ISSUE THREAD

**Issue by kaikun213** [leoTiez/htmresearch#4]
# Issue list from discussion 17/11
[E] = Test in Experiments
[C] = Cleanup
[T] = Todos
* [x] [T] Compute method in apical temporal memory
* [x] [T] Getter/Setter redefined to new variables 
* [x] [C] Initial permanence -> can be removed?
* [x] [E] Basal/Apical weights -> one segment per cell randomly initialized -> better results? (e.g. NN convergence) or hinderly?
* [x] [E] Use apical input: (1) as tiebreak, (2) not at all, (3) same weights as basal (bias only needed once)
* [x] [E] Normalization: Threshold is (1) before (independent thresholding), (2) after (competition based on threshold), (3) in-between (2-times normalize)

**Comment by leoTiez** [comment]
Closing this issue since project is submitted
